force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Subscription_Type__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Type__c</fullName>
    <label>Subscription Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Metal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContactCostInfo__c/ContactCostInfo__c.object-meta.xml
<CustomObject>
    <label>Contact Cost Info</label>
    <nameField>
        <displayFormat>CI-{000000}</displayFormat>
        <label>Contact Cost Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Cost Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ContactCostInfo__c/fields/ATM_Fee__c.field-meta.xml
<CustomField>
    <fullName>ATM_Fee__c</fullName>
    <label>ATM Fee</label>
    <precision>17</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ContactCostInfo__c/fields/Card_Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement_Cost__c</fullName>
    <label>Card Replacement Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ContactCostInfo__c/fields/Cost_Per_Month__c.field-meta.xml
<CustomField>
    <fullName>Cost_Per_Month__c</fullName>
    <label>Cost Per Month</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ContactCostInfo__c/fields/Subscription_Type__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Type__c</fullName>
    <label>SubscriptionType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Metal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CC_ContactCostAPI.cls
public class CC_ContactCostAPI {
    @AuraEnabled
    public static Map<String, Object> getContactCostInfo(String uuid) {
        Contact contact = [SELECT Id, Home_Country__c, Subscription_Type__c FROM Contact WHERE UUID__c = :uuid LIMIT 1];
        if (contact == null) {
            throw new AuraHandledException('Contact not found');
        }

        ContactCostInfo__c costInfo = [
            SELECT Cost_Per_Month__c, ATM_Fee__c, Card_Replacement_Cost__c 
            FROM ContactCostInfo__c 
            WHERE Country__c = :contact.Home_Country__c AND Subscription_Type__c = :contact.Subscription_Type__c 
            LIMIT 1
        ];
        Map<String, Object> response = new Map<String, Object>();
        response.put('CostPerMonth', costInfo.Cost_Per_Month__c);
        response.put('ATMFee', costInfo.ATM_Fee__c);
        response.put('CardReplacementCost', costInfo.Card_Replacement_Cost__c);
        
        return response;
    }
}